export interface AppLink{
    id:string;
    name:string;
    description:string;
    url:string;
    icon?:string;
    category?: 'pmo' | 'ai' | 'community' | 'training' | 'other' | 'gemini' | 'googlevids' | 'notebooklm' | 'workspace-studio' | 'ai-msi-operations' | 'gemini-knowledge-base' | 'gemini-support' | 'msi-ai-tools-list' | 'msi-genai-portal';
    isExternal?:boolean;
}
export const APP_LINKS: AppLink[]=[
    {
        id: 'pmo-portal',
        name: 'Internaltion SI PMO Portal',
        description: 'Project management and resource allocation hub',
        url: '',
        icon: '📊',
        category: 'pmo',
        isExternal: true,
    },
    /*{
        id: 'ai-planning',
        name: 'Intelligent Planning',
        description: 'Automatized Project Management Plan creation',
        url: '',
        icon: '🧠',
        category: 'ai',
        isExternal: true,
    },
    {
        id:'predictive-analytics',
        name:'Predictive Analytics',
        description:'Early risk detection & management plan adjustment',
        url:'',
        icon:'🔍',
        category:'ai',
        isExternal:true,
    },
    {
        id:'smart-collaboration',
        name:'Smart Collaboration',
        description:'AI-driven communication & insights',
        url:'',
        icon:'🎧',
        category:'ai',
        isExternal:true,
    },
    */
    {
        id:'safety-training',
        name: 'Safety and Smart: The Rules Of The AI',
        description:'Essential hygiene for the AI era.',
        url:'',
        icon:'📚',
        category:'training',
        isExternal:false,
    },
    {
        id:'community',
        name:'Community',
        description:'Join our community to connect with like-minded professionals',
        url:'',
        icon:'👥',
        category:'community',
        isExternal:true,
    },
    {
        id:'other',
        name:'Other',
        description:'Other',
        url:'',
        icon:'🌐',
        category:'other',
        isExternal:true,
    },
    {
        id:'gemini',
        name:'Gemini',
        description:'Gemini',
        url:'https://gemini.google.com',
        icon:'✨',
        category:'gemini',
        isExternal:true,
    },
    {
        id:'googlevids',
        name:'Google Vids',
        description:'Google-Vids',
        url:'https://workspace.google.com/products/vids/',
        icon:'🎥',
        category:'googlevids',
        isExternal:true,
    },
    {
        id:'notebooklm',
        name:'NotebookLM',
        description:'NotebookLM',
        url:'https://notebooklm.google.com',
        icon:'📝',
        category:'notebooklm',
        isExternal:true,
    },
    {
        id:'workspace-studio',
        name:'Workspace Studio',
        description:'Workspace Studio',
        url:'https://workspace.google.com/products/studio/',
        icon:'🎨',
        category:'workspace-studio',
        isExternal:true,
    },
    {
        id:'ai-msi-operations',
        name:'AI MSI Operations',
        description:'AI MSI Operations',
        url:'https://batchat.motorolasolutions.com/home/ls/community/generative-ai-enablement',
        icon:'🤖',
        category:'ai-msi-operations',
        isExternal:true,
    },
    {
        id:'gemini-knowledge-base',
        name:'Gemini Knowledge Base',
        description:'Gemini Knowledge Base',
        url:'https://batchat.motorolasolutions.com/home/gemini-knowledge-base-gkb',
        icon:'📚',
        category:'gemini-knowledge-base',
        isExternal:true,
    },
    {
        id:'gemini-support',
        name:'Gemini Support',
        description:'Gemini Support',
        url:'https://batchat.motorolasolutions.com/home/ls/content/4761540631509933/gemini-batchat-support-pages',
        icon:'🛠️',
        category:'gemini-support',
        isExternal:true,
    },
    {
        id:'msi-ai-tools-list',
        name:'MSI AI Tools List',
        description:'MSI AI Tools List',
        url:'https://docs.google.com/spreadsheets/d/1WbKF08kwUI2yEYbN2zxB1VNzj4tVLKSFHcgZYGNYIh8/edit?gid=2051282919#gid=2051282919',
        icon:'📋',
        category:'msi-ai-tools-list',
        isExternal:true,
    },
    {
        id:'msi-genai-portal',
        name:'MSI GenAI Portal',
        description:'MSI GenAI Portal',
        url:'https://msi-genai.stage.commandcentral.com/login',
        icon:'🌐',
        category:'msi-genai-portal',
        isExternal:true,
    }
];